### ISSUE TITLE
Support for Manjaro/Arch/Endeavour

### ISSUE THREAD

**Issue by jurassicjordan** [OpenVoiceOS/ovos-installer#58]
Operating systemd not supported.
I want to use ovos on my EndeavourOS machine, as I did with mycroft before it was shut down

**Comment by goldyfruit** [comment]
I have no plan for now to support Manjaro/Arch/Endeavour since I am not running (don't have experience with) these Linux distributions.

Currently supported distributions are:

| Distribution        | Version   |
| ------------------- | --------- |
| CentOS              | `>= 8`    |
| Debian GNU/Linux    | `>= 10`   |
| Fedora              | `>= 37`   |
| openSUSE Leap       | `>= 15`   |
| openSUSE Tumbleweed | `N/A`     |
| Raspbian            | `N/A`     |
| Raspberry Pi OS     | `N/A`     |
| Rocky Linux         | `>=8`     |
| Ubuntu              | `>=20.04` |
| WSL2                | `N/A`     |

PRs are welcome :+1:
