### ISSUE TITLE
_ovos_hardware_mark2_kernel_target is hardcoded

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-installer#84]
Now that we moved to a kernel > 6.6.22 the value of __ovos_hardware_mark2_kernel_target_ should be retrieved with `uname -r`

**Comment by denics** [comment]
More info: http://sprunge.us/uSe1sN forcing the _ovos_hardware_mark2_kernel_target variable to the actual kernel version works like charm

**Comment by goldyfruit** [comment]
Yeah for now the kernel version is hardcoded as the VocalFusionDriver has not been tested much with newer versions.

But the plan is to rely on the Debian packages for the kernel image and headers which will avoid the `rpi-update` amd `rpi-source` tasks.

In order to improve this as well, I pushed a DKMS feature couple weeks ago. https://github.com/OpenVoiceOS/VocalFusionDriver/commit/96e1219d99681a6957daf451f59050ebc6c19508

**Comment by denics** [comment]
Should be fixed with #88
